---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patches:
  - path: application_patch.yaml

# Override the image to a local tag so Tilt can inject the image it built.
# `application_customizations.yaml` (in base) tells kustomize to look for
# this image in spec/deployment/image of PlatformApplication resources.
images:
  - name: {{ image_registry }}/{{ org-solution-name }}/{{ project-name }}
    newName: {{ project-name }}
    newTag: local
