---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - namespace.yaml

# Solution-scoped namespace (see dev overlay for rationale).
namespace: {{ org-solution-name }}-{{ project-name }}-prd

patches:
  - path: application_patch.yaml
